# Generated by Django 4.1.5 on 2023-01-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=200, null=True)),
                ("Added_Date", models.DateTimeField(auto_now_add=True, null=True)),
                ("Passport_Number", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
