# Generated by Django 4.1.5 on 2023-01-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("from", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=200, null=True)),
                ("E_mail", models.EmailField(max_length=200, null=True)),
                ("Phone_Number", models.IntegerField(null=True)),
                ("Country", models.CharField(max_length=200, null=True)),
                ("City", models.CharField(max_length=200)),
                ("State", models.CharField(max_length=200)),
                ("Zip_Code", models.IntegerField()),
                ("Address", models.CharField(max_length=200)),
                ("FIG_License_Number", models.IntegerField(null=True)),
                ("Passport_Number", models.IntegerField(null=True)),
            ],
        ),
    ]
