# Generated by Django 4.1.5 on 2023-02-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('from', '0005_gender_music_passport_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Area_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='FIG_License_Number',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='Passport_Number',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='Phone_Number',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='State',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Zip_Code',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='Passport_Number',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='username',
            name='Passport_Number',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='username',
            name='Phone',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
