# Generated by Django 4.1.5 on 2023-02-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('from', '0009_alter_contact_fig_license_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='FIG_License_Number',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Passport_Number',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Phone_Number',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='passport',
            name='Passport_Number',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='Passport_Number',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='travel',
            name='Flight_Number',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='username',
            name='Passport_Number',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='username',
            name='Phone',
            field=models.PositiveBigIntegerField(),
        ),
    ]
