# Generated by Django 4.1.5 on 2023-02-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('from', '0010_alter_contact_fig_license_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='FIG_License_Number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Passport_Number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Phone_Number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
