# Generated by Django 4.1.5 on 2023-02-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('from', '0011_alter_contact_fig_license_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Phone_Number',
            field=models.IntegerField(default=0),
        ),
    ]
