# Generated by Django 4.1.5 on 2023-02-03 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('from', '0015_userprofile_delete_contactprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='UserProfile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='from.userprofile'),
            preserve_default=False,
        ),
    ]
