# Generated by Django 4.1.5 on 2023-02-03 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('from', '0017_remove_contact_userprofile_contactprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gender',
        ),
        migrations.DeleteModel(
            name='player',
        ),
    ]
