# Generated by Django 4.1.5 on 2023-02-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('from', '0018_delete_gender_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Added_Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Passport_Number', models.PositiveBigIntegerField()),
            ],
        ),
    ]
