# Generated by Django 4.1.5 on 2023-02-03 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('from', '0019_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='UserProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='from.userprofile'),
        ),
    ]
