# Generated by Django 4.1.5 on 2023-02-04 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('from', '0027_contact_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='contact',
            name='UserProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='from.userprofile'),
        ),
    ]
