# Generated by Django 4.1.5 on 2023-02-04 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('from', '0028_remove_contact_user_id_alter_contact_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='UserProfile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
